version: '3.8'

services:
  web:
    container_name: full_api
    build: .
    ports:
      - 3909:3909
    command: go run cmd/main.go
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=challenge
